### ISSUE TITLE
Allow override configs

### ISSUE THREAD

**Issue by souporserious** [kitze/create-react-app#46]
How do you feel about allowing custom babel and webpack configs? It looks like we can add this pretty easy after seeing [this PR](https://github.com/facebookincubator/create-react-app/pull/1317/files). NextJS did something similar, there is some good info about it in [this thread](https://github.com/zeit/next.js/pull/222). Facebook Incubator sounds like they won't even consider it until late 2017 😕

**Comment by kitze** [comment]
There is a good reason that Facebook doesn't want custom configs in CRA. My forked version uses only a certain number of features because I can be 100% sure that every combination of the features will work fine. 

If we allow custom configs, a bunch of new issues will come up because *some* combination of features won't work.

For now this will be closed, sorry.
